import Foundation                                                                                                                                                                                                                    
import Scenes                                                                                                                                                                                                                        
import Igis                                                                                                                                                                                                                          
                                                                                                                                                                                                                                     
/*                                                                                                                                                                                                                                   
 This class is responsible for rendering the background.                                                                                                                                                                             
 */                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                     
class Background : RenderableEntity {                                                                                                                                                                                                
    let WorldImage : Image                                                                                                                                                                                                           
    var diffBackground = 0                                                                                                                                                                                                           
    private var BackPoint = Point(x:0,y:0)                                                                                                                                                                                           
    init() {                                                                                                                                                                                                                         
        // Using a meaningful name can be helpful for debugging                                                                                                                                                                      
        guard let WorldImageURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/1-1.png") else {                                                                                                                  
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
        WorldImage = Image(sourceURL:WorldImageURL)                                                                                                                                                                                  
        super.init(name:"Background")                                                                                                                                                                                                
                                                                                                                                                                                                                                     
    }                                                                                                                                                                                                                                
    func render(rectRowBuildingCount: Int, canvas:Canvas, topLeft:Point, size:Size, color:Color, fillcolor:Color,line:Int){                                                                                                          
        var rect = Rect(topLeft:topLeft, size:size)                                                                                                                                                                                  
        for _ in 0 ..< rectRowBuildingCount {                                                                                                                                                                                        
            let rectangle = Rectangle(rect:rect,fillMode:.fillAndStroke)                                                                                                                                                             
            let fillstyle = FillStyle(color:fillcolor)                                                                                                                                                                               
            let strokeStyle = StrokeStyle(color:color)                                                                                                                                                                               
            let linewidth = LineWidth(width:line)                                                                                                                                                                                    
            canvas.render(fillstyle,strokeStyle,linewidth,rectangle)                                                                                                                                                                 
            rect.topLeft = Point(x:rect.topLeft.x+size.width,y:rect.topLeft.y)                                                                                                                                                       
        }                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
    override func setup(canvasSize:Size,canvas:Canvas){                                                                                                                                                                              
        canvas.setup(WorldImage)                                                                                                                                                                                                     
    }                                                                                                                                                                                                                                
    func moveBackGround(_ amount:Int){                                                                                                                                                                                               
        BackPoint.x -= amount                                                                                                                                                                                                        
    }                                                                                                                                                                                                                                
    override func render(canvas:Canvas){                                                                                                                                                                                             
        guard let canvasSize = canvas.canvasSize else {                                                                                                                                                                              
            fatalError("no canvas Size")                                                                                                                                                                                             
        }                                                                                                                                                                                                                            
        switch diffBackground {                                                                                                                                                                                                      
        case 0:                                                                                                                                                                                                                      
            let skyBlue = Color(red:90,green:150,blue:255)                                                                                                                                                                           
            render(rectRowBuildingCount:1,canvas:canvas,topLeft:Point(x:0,y:0),size:canvasSize,color:skyBlue,fillcolor:skyBlue,line:1)                                                                                               
            if WorldImage.isReady{                                                                                                                                                                                                   
                WorldImage.renderMode = .destinationRect(Rect(topLeft:BackPoint, size:Size(width:canvasSize.width*8, height:canvasSize.height)))    
                 canvas.render(WorldImage)                                                                                                                                                                                            
            }                                                                                                                                                                                                                        
        case 1:                                                                                                                                                                                                                      
            render(rectRowBuildingCount:1,canvas:canvas,topLeft:Point(x:0,y:0),size:canvasSize,color:Color(.black),fillcolor:Color(.black),line:1)                                                                                   
                                                                                                                                                                                                                                     
        default:                                                                                                                                                                                                                     
            fatalError("there is no background associated with \(diffBackground)")                                                                                                                                                   
        }                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                
    func changeBackground(_ num: Int){                                                                                                                                                                                               
        diffBackground = num                                                                                                                                                                                                         
    }                                                                                                                                                                                                                                
}               