import Igis                                                                                                                                                                                                                          
import Scenes                                                                                                                                                                                                                        
import Foundation                                                                                                                                                                                                                    
class Foreground : RenderableEntity{                                                                                                                                                                                                 
    let benFace : Image                                                                                                                                                                                                              
    private var benSize = Size(width:200,height:300)                                                                                                                                                                                 
    var benTime = 60                                                                                                                                                                                                                 
    private func mainScene() -> MainScene {                                                                                                                                                                                          
        guard let scene = scene as? MainScene else {                                                                                                                                                                                 
            fatalError("MainScene required")                                                                                                                                                                                         
        }                                                                                                                                                                                                                            
        return scene                                                                                                                                                                                                                 
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
    init() {                                                                                                                                                                                                                         
        guard let benFaceURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/jesus.png") else{                                                                                                                    
            fatalError("could not get the jesus pick")                                                                                                                                                                               
        }                                                                                                                                                                                                                            
        benFace = Image(sourceURL:benFaceURL)                                                                                                                                                                                        
        super.init(name:"Foreground")                                                                                                                                                                                                
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
    override func setup(canvasSize:Size,canvas:Canvas){                                                                                                                                                                              
        canvas.setup(benFace)                                                                                                                                                                                                        
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
    override func render(canvas:Canvas){                                                                                                                                                                                             
        guard let canvasSize = canvas.canvasSize else {                                                                                                                                                                              
            fatalError("no canvas Size")                                                                                                                                                                                             
        }                                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
        if mainScene().interactionLayer.mario.getHitpoint() == 0 {                                                                                                                                                                   
            if benTime > 0 {                                                                                                                                                                                                         
                benTime -= 1                                                                                                                                                                                                         
            }                                                                                                                                                                                                                        
            benSize.width += 5                                                                                                                                                                                                       
            benSize.height += 3                                                                                                                                                                                                      
            ScenesShell.render(rectRowBuildingCount: 1, canvas: canvas, topLeft:Point(x:0,y:0), size: canvasSize, color:Color(.black), fillcolor:Color(.black), line: 1)                                                             
                                                                                                                                                                                                                                     
            let deadWords = Text(location:Point(x:canvasSize.width/3,y:canvasSize.height/2), text:"Ha you died you suck")                                                                                                            
                                                                                                                                                                                                                                     
            deadWords.fillMode = .fillAndStroke                                                                                                                                                                                      
            let wordFill = FillStyle(color:Color(.white))                                                                                                                                                                            
            let wordStroke = StrokeStyle(color:Color(.red))                                                                                                                                                                          
            let linewidth = LineWidth(width:1)                                                                                                                                                                                       
            let font = canvasSize.width/50                                                                                                                                                                                           
            deadWords.font = " \(font)pt Arial"                                                                                                                                                                                      
            canvas.render(wordStroke,wordFill,deadWords)                                                                                                                                                                             
            if benFace.isReady && benTime == 0{                                                                                                                                                                                      
                benFace.renderMode = .destinationRect(Rect(topLeft:Point(x:canvasSize.width/2-benSize.width/2,y:canvasSize.height/2-benSize.height/2), size:benSize))                                                                
                canvas.render(benFace) 
                }                                                                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                
}                                                                                                                                                                                                                                    
     