import Igis                                                                                                                                                                                                                          
import Scenes                                                                                                                                                                                                                        
import Foundation                                                                                                                                                                                                                    
class Goomba : RenderableEntity {                                                                                                                                                                                                    
    private var location : Point                                                                                                                                                                                                     
    private let aiAspects : Int                                                                                                                                                                                                      
    private let GoombaLeftFoot : Image                                                                                                                                                                                               
    private let GoombaRightFoot : Image                                                                                                                                                                                              
    private let deadGoomba : Image                                                                                                                                                                                                   
    private var loop = 0                                                                                                                                                                                                             
    private let MaxFrameCount = 16                                                                                                                                                                                                   
    private let goombaSpeed = 2                                                                                                                                                                                                      
    private var isDead = false                                                                                                                                                                                                       
    private var GoombaSize = Size(width:0,height:0)                                                                                                                                                                                  
    init(location: Point, aiAspects:Int){                                                                                                                                                                                            
        self.location = location                                                                                                                                                                                                     
        self.aiAspects = aiAspects                                                                                                                                                                                                   
        guard let GoombaLeftFootURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/Goomba.png") else {                                                                                                           
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
        guard let GoombaRightFootURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/GoombaRight.png") else {                                                                                                     
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
        guard let deadGoombaURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/DeadGoomba.png") else {                                                                                                           
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
        GoombaLeftFoot = Image(sourceURL:GoombaLeftFootURL)                                                                                                                                                                          
        GoombaRightFoot = Image(sourceURL:GoombaRightFootURL)                                                                                                                                                                        
        deadGoomba = Image(sourceURL:deadGoombaURL)                                                                                                                                                                                  
        super.init(name:"Goomba")                                                                                                                                                                                                    
    }                                                                                                                                                                                                                                
    override func setup(canvasSize:Size,canvas:Canvas){                                                                                                                                                                              
        canvas.setup(GoombaLeftFoot,GoombaRightFoot)                                                                                                                                                                                 
        GoombaSize = Size(width:canvasSize.width/26,height:canvasSize.height/15)                                                                                                                                                     
    }                                                                                                                                                                                                                                
    func move(to point:Point) {                                                                                                                                                                                                      
        location = point                                                                                                                                                                                                             
    }                                                                                                                                                                                                                                
    override func render(canvas:Canvas){                                                                                                                                                                                             
        guard let canvasSize = canvas.canvasSize else {                                                                                                                                                                              
            fatalError("no canvas Size")                                                                                                                                                                                             
        }                                                                                                                                                                                                                            
        //ScenesShell.render(rectRowBuildingCount:1,canvas:canvas,topLeft:location,size:GoombaSize,color:Color(.black),fillcolor:Color(.black),line:1)                                                                               
                                                                                                                                                                                                                                     
        loop = (loop+1)%MaxFrameCount                                                                                                                                                                                                
        if !isDead {  
            if GoombaLeftFoot.isReady && loop > MaxFrameCount/2 {                                                                                                                                                                    
                GoombaLeftFoot.renderMode = .destinationRect(Rect(topLeft:location, size:GoombaSize))                                                                                                                                
                canvas.render(GoombaLeftFoot)                                                                                                                                                                                        
                                                                                                                                                                                                                                     
            }                                                                                                                                                                                                                        
            if GoombaRightFoot.isReady && loop <= MaxFrameCount/2{                                                                                                                                                                   
                GoombaRightFoot.renderMode = .destinationRect(Rect(topLeft:location, size:GoombaSize))                                                                                                                               
                canvas.render(GoombaRightFoot)                                                                                                                                                                                       
                                                                                                                                                                                                                                     
            }                                                                                                                                                                                                                        
        }else {                                                                                                                                                                                                                      
            if  deadGoomba.isReady{                                                                                                                                                                                                  
                deadGoomba.renderMode = .destinationRect(Rect(topLeft:location, size:GoombaSize))                                                                                                                                    
                canvas.render(deadGoomba)                                                                                                                                                                                            
            }                                                                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
        location.x += goombaSpeed                                                                                                                                                                                                    
                                                                                                                                                                                                                                     
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
    override func boundingRect() -> Rect {                                                                                                                                                                                           
        return Rect(topLeft:location,size:GoombaSize)                                                                                                                                                                                
    }                                                                                                                                                                                                                                
    func getLocation() -> Point {                                                                                                                                                                                                    
        return location 
        }                                                                                                                                                                                                                                
    public func died() {                                                                                                                                                                                                             
        isDead = true                                                                                                                                                                                                                
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
} 