import Scenes                                                                                                                                                                                                                        
import Foundation                                                                                                                                                                                                                    
                                                                                                                                                                                                                                     
class Ground : RenderableEntity{                                                                                                                                                                                                     
    private let Ground : Image                                                                                                                                                                                                       
    private var BlockSize : Size                                                                                                                                                                                                     
    private let columnCount : Int                                                                                                                                                                                                    
    private let rowCount : Int                                                                                                                                                                                                       
    private var location : Point                                                                                                                                                                                                     
                                                                                                                                                                                                                                     
    init(location:Point,columnCount:Int,rowCount:Int){                                                                                                                                                                               
        guard let GroundURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/GroundBlock.png") else {                                                                                                              
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
        }                                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
        self.location = location                                                                                                                                                                                                     
        self.columnCount = columnCount                                                                                                                                                                                               
        self.rowCount = rowCount                                                                                                                                                                                                     
        BlockSize = Size(width:0,height:0)                                                                                                                                                                                           
        Ground = Image(sourceURL:GroundURL)                                                                                                                                                                                          
        super.init(name:"Ground")                                                                                                                                                                                                    
    }                                                                                                                                                                                                                                
    override func setup(canvasSize:Size,canvas:Canvas){                                                                                                                                                                              
                                                                                                                                                                                                                                     
        canvas.setup(Ground)                                                                                                                                                                                                         
        BlockSize = Size(width:canvasSize.width/26, height:canvasSize.height/15)                                                                                                                                                     
    }                                                                                                                                                                                                                                
    func render(rectRowBuildingCount: Int, canvas:Canvas, topLeft:Point, size:Size, color:Color, fillcolor:Color,line:Int){                                                                                                          
        var rect = Rect(topLeft:topLeft, size:size)                                                                                                                                                                                  
        for _ in 0 ..< rectRowBuildingCount {                                                                                                                                                                                        
            let rectangle = Rectangle(rect:rect,fillMode:.fillAndStroke)                                                                                                                                                             
            let fillstyle = FillStyle(color:fillcolor)                                                                                                                                                                               
            let strokeStyle = StrokeStyle(color:color)                                                                                                                                                                               
            let linewidth = LineWidth(width:line)                                                                                                                                                                                    
            canvas.render(fillstyle,strokeStyle,linewidth,rectangle)                                                                                                                                                                 
            rect.topLeft = Point(x:rect.topLeft.x+size.width,y:rect.topLeft.y)                                                                                                                                                       
        }                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
    override func render(canvas:Canvas){                                                                                                                                                                                             
        guard let canvasSize = canvas.canvasSize else {                                                                                                                                                                              
            fatalError("no canvas Size")                                                                                                                                                                                             
        }                                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
        if Ground.isReady{                                                                                                                                                                                                           
            Ground.renderMode = .destinationRect(Rect(topLeft:Point(x:0,y:(canvasSize.height)), size:BlockSize))                                                                                                                     
            for upper in 1...columnCount{                                                                                                                                                                                            
                for index in 0..<rowCount{                                                                                                                                                                                           
                    Ground.renderMode = .destinationRect(Rect(topLeft:Point(x:location.x+((index)*BlockSize.width),y:(canvasSize.height-(upper*(BlockSize.height)))), size:BlockSize))                                               
                    canvas.render(Ground)
                                                                                                                                                                                                                                      
                }                                                                                                                                                                                                                    
                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                     
            }                                                                                                                                                                                                                        
        }                                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
    func move(to point: Point){                                                                                                                                                                                                      
        location = point                                                                                                                                                                                                             
    }                                                                                                                                                                                                                                
    func getLocation() -> Point{                                                                                                                                                                                                     
        return location                                                                                                                                                                                                              
    }                                                                                                                                                                                                                                
    override func boundingRect() -> Rect{                                                                                                                                                                                            
        return Rect(topLeft:location,size:Size(width:BlockSize.width*rowCount,height:BlockSize.height*columnCount))                                                                                                                  
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                     
}  