import Scenes                                                                                                                                                                                                                        
import Igis                                                                                                                                                                                                                          
/*                                                                                                                                                                                                                                   
 This class is responsible for the interaction Layer.                                                                                                                                                                                
 Internally, it maintains the RenderableEntities for this layer.                                                                                                                                                                     
 */                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                     
class InteractionLayer : Layer,KeyDownHandler, KeyUpHandler {                                                                                                                                                                        
    public let mario = Mario()                                                                                                                                                                                                       
    let ground = Ground(location:Point(x:0,y:0),columnCount:2,rowCount:69)                                                                                                                                                           
    let goomba = Goomba(location:Point(x:0,y:0),aiAspects:1)                                                                                                                                                                         
    let ground2 = Ground(location:Point(x:0,y:0),columnCount:2,rowCount:81)                                                                                                                                                          
    let ground3 = Ground(location:Point(x:0,y:0),columnCount:2,rowCount:56)                                                                                                                                                          
    let pole = Pole()                                                                                                                                                                                                                
    private var isGravity = true                                                                                                                                                                                                     
    private var move = false                                                                                                                                                                                                         
    private var isForward = false                                                                                                                                                                                                    
    private var runningSpeed = 5                                                                                                                                                                                                     
    private var isJumping = false                                                                                                                                                                                                    
    private var jumpingHeight = 40                                                                                                                                                                                                   
    private var gravityVelocity = 18                                                                                                                                                                                                 
    private var gravity  = 1                                                                                                                                                                                                         
    private var isGrounded = true                                                                                                                                                                                                    
    private var maxSpeed = 5                                                                                                                                                                                                         
    init() {                                                                                                                                                                                                                         
        // Using a meaningful name can be helpful for debugging                                                                                                                                                                      
        super.init(name:"Interaction")                                                                                                                                                                                               
        insert(entity:ground,at:.front)                                                                                                                                                                                              
        insert(entity:ground2,at:.front)                                                                                                                                                                                             
        insert(entity:ground3,at:.front)                                                                                                                                                                                             
        insert(entity:goomba,at:.front)                                                                                                                                                                                              
        insert(entity:mario,at:.front)                                                                                                                                                                                               
        insert(entity:pole,at:.front)                                                                                                                                                                                                
        // We insert our RenderableEntities in the constructor                                                                                                                                                                       
                                                                                                                                                                                                                                     
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
    func background() -> Background {                                                                                                                                                                                                
        guard let mainScene = scene as? MainScene else {                                                                                                                                                                             
            fatalError("mainScene of type MainScene is required")                                                                                                                                                                    
        }                                                                                                                                                                                                                            
        let backgroundLayer = mainScene.backgroundLayer                                                                                                                                                                              
        let background = backgroundLayer.background                                                                                                                                                                                  
        return background                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
    override func preSetup(canvasSize: Size, canvas: Canvas) {                                                                                                                                                                       
        dispatcher.registerKeyDownHandler(handler: self)                                                                                                                                                                             
        dispatcher.registerKeyUpHandler(handler: self)                                                                                                                                                                               
        ground.move(to: Point(x:0,y:(canvasSize.height/15)*13)) 
        ground2.move(to: Point(x:canvasSize.width/26*71,y:(canvasSize.height/15)*13))                                                                                                                                                
        ground3.move(to: Point(x:canvasSize.width/26*154,y:(canvasSize.height/15)*13))                                                                                                                                               
        pole.move(to:Point(x:canvasSize.width/26*197,y:(canvasSize.height/15)*3))                                                                                                                                                    
        if mario.getHitpoint() == 2{                                                                                                                                                                                                 
            mario.move(to: Point(x:0,y:(canvasSize.height/15)*12))                                                                                                                                                                   
        } else if mario.getHitpoint() == 1{                                                                                                                                                                                          
            mario.move(to: Point(x:0,y:(canvasSize.height/15)*12))                                                                                                                                                                   
        }                                                                                                                                                                                                                            
        goomba.move(to:Point(x:(canvasSize.width/2),y:(canvasSize.height/15)*12))                                                                                                                                                    
        maxSpeed = canvasSize.width/200                                                                                                                                                                                              
                                                                                                                                                                                                                                     
        jumpingHeight = canvasSize.height/20                                                                                                                                                                                         
        gravityVelocity = jumpingHeight/2                                                                                                                                                                                            
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
    override func postTeardown(){                                                                                                                                                                                                    
        dispatcher.unregisterKeyDownHandler(handler: self)                                                                                                                                                                           
        dispatcher.unregisterKeyUpHandler(handler: self)                                                                                                                                                                             
                                                                                                                                                                                                                                     
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
    func onKeyUp(key:String,code:String,ctrlKey:Bool,shiftKey:Bool,altKey:Bool,metaKey:Bool){                                                                                                                                        
                                                                                                                                                                                                                                     
        if key == "d" || key == "D"{                                                                                                                                                                                                 
            move = false 
            mario.changeAnimation(0)                                                                                                                                                                                                 
        }                                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
        if key == "w" || key == "W"{                                                                                                                                                                                                 
            isJumping = false                                                                                                                                                                                                        
            mario.changeAnimation(0)                                                                                                                                                                                                 
            jumpingHeight = 0                                                                                                                                                                                                        
        }                                                                                                                                                                                                                            
        if  isGravity && key == "a" || key == "A"{                                                                                                                                                                                   
            move = false                                                                                                                                                                                                             
                                                                                                                                                                                                                                     
            runningSpeed = maxSpeed                                                                                                                                                                                                  
            mario.changeAnimation(0)                                                                                                                                                                                                 
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
        if !shiftKey{                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
            runningSpeed = maxSpeed                                                                                                                                                                                                  
            mario.runningAnimation(false)                                                                                                                                                                                            
        }                                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
    func onKeyDown(key:String,code:String,ctrlKey:Bool,shiftKey:Bool,altKey:Bool,metaKey:Bool){    
                                                                                                                                                                                                                                       
        if key == "d" || key == "D" {                                                                                                                                                                                                
            isForward = true                                                                                                                                                                                                         
            move = true                                                                                                                                                                                                              
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
        if key == "w" || key == "W" {                                                                                                                                                                                                
            isJumping = true                                                                                                                                                                                                         
        }                                                                                                                                                                                                                            
        if key == "a" || key == "A"{                                                                                                                                                                                                 
            isForward = false                                                                                                                                                                                                        
            move = true                                                                                                                                                                                                              
            runningSpeed = maxSpeed                                                                                                                                                                                                  
        }                                                                                                                                                                                                                            
        if shiftKey{                                                                                                                                                                                                                 
            runningSpeed = maxSpeed*2                                                                                                                                                                                                
            mario.runningAnimation(true)                                                                                                                                                                                             
        }                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
    override func postCalculate(canvas:Canvas){                                                                                                                                                                                      
        guard let canvasSize = canvas.canvasSize else {                                                                                                                                                                              
            fatalError("no canvas Size")                                                                                                                                                                                             
        }                                                                                                                                                                                                                            
        if isGravity {
             mario.move(to: Point(x:mario.getLocation().x,y:mario.getLocation().y+gravityVelocity))                                                                                                                                       
        goomba.move(to: Point(x:goomba.getLocation().x,y:goomba.getLocation().y+gravityVelocity))                                                                                                                                    
        }                                                                                                                                                                                                                            
        ///////////////////////////////////////////////////////////////////////////                                                                                                                                                  
        // hit detection with ground blocks                                                                                                                                                                                          
        ///////////////////////////////////////////////////////////////////////////                                                                                                                                                  
                                                                                                                                                                                                                                     
        // topHit detection                                                                                                                                                                                                          
        let GroundBoundingRect = ground.boundingRect()                                                                                                                                                                               
        let marioBoundingRect = mario.boundingRect()                                                                                                                                                                                 
        let groundContainment = GroundBoundingRect.containment(target: marioBoundingRect)                                                                                                                                            
        let goombaBoundingRect = goomba.boundingRect()                                                                                                                                                                               
        let goombaContainment = GroundBoundingRect.containment(target: goombaBoundingRect)                                                                                                                                           
        let GroundBoundingRect2 = ground2.boundingRect()                                                                                                                                                                             
        let groundContainment2 = GroundBoundingRect2.containment(target: marioBoundingRect)                                                                                                                                          
        let GroundBoundingRect3 = ground3.boundingRect()                                                                                                                                                                             
        let groundContainment3 = GroundBoundingRect3.containment(target: marioBoundingRect)                                                                                                                                          
        let GoombaMario = marioBoundingRect.containment(target: goombaBoundingRect)                                                                                                                                                  
        let poleBoundingRect = pole.boundingRect()                                                                                                                                                                                   
        let poleContainment = poleBoundingRect.containment(target: marioBoundingRect)                                                                                                                                                
                                                                                                                                                                                                                                     
        if !groundContainment.intersection([.overlapsTop]).isEmpty && !groundContainment.intersection([.containedHorizontally]).isEmpty || !groundContainment2.intersection([.overlapsTop]).isEmpty && !groundContainment2.intersection([.containedHorizontally]).isEmpty || !groundContainment3.intersection([.overlapsTop]).isEmpty && !groundContainment3.intersection([.containedHorizontally]).isEmpty{                                                             
            jumpingHeight = canvasSize.height/20                                                                                                                                                                                     
            if mario.getHitpoint() == 1{  
                mario.move(to: Point(x:mario.getLocation().x,y:(canvasSize.height/15)*12))                                                                                                                                           
                                                                                                                                                                                                                                     
            }else {                                                                                                                                                                                                                  
                                                                                                                                                                                                                                     
                mario.move(to: Point(x:mario.getLocation().x,y:(canvasSize.height/15)*11))                                                                                                                                           
            }                                                                                                                                                                                                                        
            mario.changeAnimation(0)                                                                                                                                                                                                 
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
        if !poleContainment.intersection([.contact]).isEmpty || !poleContainment.intersection([.overlapsLeft,.overlapsHorizontally,.containedHorizontally,.overlapsRight]).isEmpty{                                                  
            background().changeBackground(1)                                                                                                                                                                                         
            isGravity = false                                                                                                                                                                                                        
            remove(entity:pole)                                                                                                                                                                                                      
            remove(entity:ground)                                                                                                                                                                                                    
            remove(entity:ground2)                                                                                                                                                                                                   
            remove(entity:ground3)                                                                                                                                                                                                   
            remove(entity:goomba)                                                                                                                                                                                                    
            remove(entity:pole)                                                                                                                                                                                                      
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
        ///////////////////////////////////////////////////////////////////////////                                                                                                                                                  
        //Goomba continment                                                                                                                                                                                                          
        ///////////////////////////////////////////////////////////////////////////                                                                                                                                                  
                                                                                                                                                                                                                                     
        if !goombaContainment.intersection([.overlapsTop]).isEmpty && !goombaContainment.intersection([.containedHorizontally]).isEmpty{   
             goomba.move(to: Point(x:goomba.getLocation().x,y:(canvasSize.height/15)*12))                                                                                                                                             
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
        if  !GoombaMario.intersection([.contact]).isEmpty{                                                                                                                                                                           
            if mario.getMode() == 0 {                                                                                                                                                                                                
                   mario.gotHit()                                                                                                                                                                                                    
               }                                                                                                                                                                                                                     
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
        //////////////////////////////////////////////////                                                                                                                                                                           
        // left Hit detection                                                                                                                                                                                                        
        //////////////////////////////////////////////////                                                                                                                                                                           
                                                                                                                                                                                                                                     
        if !groundContainment.intersection([.overlapsLeft]).isEmpty && !groundContainment.intersection([.containedVertically]).isEmpty{                                                                                              
            mario.move(to: Point(x:ground.getLocation().x,y:mario.getLocation().y))                                                                                                                                                  
        }                                                                                                                                                                                                                            
        ///////////////////////////////////////////////////////////////////////////                                                                                                                                                  
        // gravity                                                                                                                                                                                                                   
        ///////////////////////////////////////////////////////////////////////////                                                                                                                                                  
                                                                                                                                                                                                                                     
        if !groundContainment.intersection([ .beyondTop]).isEmpty ||  !groundContainment2.intersection([ .beyondTop]).isEmpty  || !groundContainment3.intersection([ .beyondTop]).isEmpty {                                          
            mario.changeAnimation(3)                                                                                                                                                                                                 
            if jumpingHeight >= 0{                                                                                                                                                                                                   
                jumpingHeight -= gravity 
                }                                                                                                                                                                                                                        
            if jumpingHeight < 0 {                                                                                                                                                                                                   
                jumpingHeight = 0                                                                                                                                                                                                    
            }                                                                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
        ///////////////////////////////////////////////////////////////////////////                                                                                                                                                  
        // moves forward and backwards                                                                                                                                                                                               
        ///////////////////////////////////////////////////////////////////////////                                                                                                                                                  
                                                                                                                                                                                                                                     
        if move{                                                                                                                                                                                                                     
            if isForward{                                                                                                                                                                                                            
                if groundContainment.intersection([ .beyondTop,.beyondHorizontally]).isEmpty ||   groundContainment2.intersection([ .beyondTop,.beyondHorizontally]).isEmpty || groundContainment3.intersection([ .beyondTop,.beyondHorizontally]).isEmpty{                                                                                                                                                                                                              
                                                                                                                                                                                                                                     
                    mario.changeAnimation(1)                                                                                                                                                                                         
                }                                                                                                                                                                                                                    
                mario.move(to:Point(x:mario.getLocation().x+runningSpeed,y:mario.getLocation().y) )                                                                                                                                  
            }else {                                                                                                                                                                                                                  
                if groundContainment.intersection([ .beyondTop,.beyondHorizontally]).isEmpty || groundContainment2.intersection([ .beyondTop,.beyondHorizontally]).isEmpty || groundContainment3.intersection([ .beyondTop,.beyondHorizontally]).isEmpty{                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
                    mario.changeAnimation(2)                                                                                                                                                                                         
                }                                                                                                                                                                                                                    
                mario.move(to:Point(x:mario.getLocation().x-runningSpeed,y:mario.getLocation().y) )  
                }                                                                                                                                                                                                                        
        }                                                                                                                                                                                                                            
        ///////////////////////////////////////////////////////////////////////////                                                                                                                                                  
        //jumps                                                                                                                                                                                                                      
        ///////////////////////////////////////////////////////////////////////////                                                                                                                                                  
                                                                                                                                                                                                                                     
        if isJumping{                                                                                                                                                                                                                
            mario.changeAnimation(3)                                                                                                                                                                                                 
                                                                                                                                                                                                                                     
            mario.move(to:Point(x:mario.getLocation().x,y:mario.getLocation().y-jumpingHeight))                                                                                                                                      
        }                                                                                                                                                                                                                            
        // moves screen forward and backwards                                                                                                                                                                                        
        if mario.getLocation().x > canvasSize.width/2 {                                                                                                                                                                              
            background().moveBackGround(runningSpeed)                                                                                                                                                                                
            ground.move(to: Point(x:ground.getLocation().x-runningSpeed,y:ground.getLocation().y))                                                                                                                                   
            ground2.move(to: Point(x:ground2.getLocation().x-runningSpeed,y:ground2.getLocation().y))                                                                                                                                
            ground3.move(to: Point(x:ground3.getLocation().x-runningSpeed,y:ground3.getLocation().y))                                                                                                                                
            mario.move(to: Point(x:canvasSize.width/2,y:mario.getLocation().y))                                                                                                                                                      
            goomba.move(to: Point(x:goomba.getLocation().x-runningSpeed,y:goomba.getLocation().y))                                                                                                                                   
            pole.move(to: Point(x:pole.getPoint().x-runningSpeed,y:pole.getPoint().y))                                                                                                                                               
        }                                                                                                                                                                                                                            
        if mario.getLocation().x < (canvasSize.width/13) {                                                                                                                                                                           
            if ground.getLocation().x < -1 {                                                                                                                                                                                         
                ground.move(to: Point(x:ground.getLocation().x+runningSpeed,y:ground.getLocation().y))                                                                                                                               
                ground2.move(to: Point(x:ground2.getLocation().x+runningSpeed,y:ground2.getLocation().y))
                ground3.move(to: Point(x:ground3.getLocation().x+runningSpeed,y:ground3.getLocation().y))                                                                                                                            
                pole.move(to: Point(x:pole.getPoint().x+runningSpeed,y:pole.getPoint().y))                                                                                                                                           
                background().moveBackGround(-runningSpeed)                                                                                                                                                                           
                goomba.move(to: Point(x:goomba.getLocation().x+runningSpeed,y:goomba.getLocation().y))                                                                                                                               
                                                                                                                                                                                                                                     
            }                                                                                                                                                                                                                        
            mario.move(to: Point(x:(canvasSize.width/13),y:mario.getLocation().y))                                                                                                                                                   
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                
    func getMario() -> Mario{                                                                                                                                                                                                        
        return self.mario                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                     
}         