import Igis                                                                                                                                                                                                                          
/*                                                                                                                                                                                                                                   
 This main code is responsible for starting Igis and initializing                                                                                                                                                                    
 the Director.                                                                                                                                                                                                                       
 It rarely needs to be altered.                                                                                                                                                                                                      
 */                                                                                                                                                                                                                                  
func render(rectRowBuildingCount: Int, canvas:Canvas, topLeft:Point, size:Size, color:Color, fillcolor:Color,line:Int){                                                                                                              
    var rect = Rect(topLeft:topLeft, size:size)                                                                                                                                                                                      
    for _ in 0 ..< rectRowBuildingCount {                                                                                                                                                                                            
        let rectangle = Rectangle(rect:rect,fillMode:.fillAndStroke)                                                                                                                                                                 
        let fillstyle = FillStyle(color:fillcolor)                                                                                                                                                                                   
        let strokeStyle = StrokeStyle(color:color)                                                                                                                                                                                   
        let linewidth = LineWidth(width:line)                                                                                                                                                                                        
        canvas.render(fillstyle,strokeStyle,linewidth,rectangle)                                                                                                                                                                     
        rect.topLeft = Point(x:rect.topLeft.x+size.width,y:rect.topLeft.y)                                                                                                                                                           
    }                                                                                                                                                                                                                                
}                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                     
print("Starting...")                                                                                                                                                                                                                 
do {                                                                                                                                                                                                                                 
    let igis = Igis()                                                                                                                                                                                                                
    try igis.run(painterType:ShellDirector.self)                                                                                                                                                                                     
} catch (let error) {                                                                                                                                                                                                                
    print("Error: \(error)")                                                                                                                                                                                                         
}                                                                                                                                                                                                                                    
 