import Igis                                                                                                                                                                                                                          
import Scenes                                                                                                                                                                                                                        
import Foundation                                                                                                                                                                                                                    
class Mario : RenderableEntity {                                                                                                                                                                                                     
    let LeftLegUP : Image                                                                                                                                                                                                            
    let LeftLegBack : Image                                                                                                                                                                                                          
    let LeftLegMiddle : Image                                                                                                                                                                                                        
    let backLeftLegUP : Image                                                                                                                                                                                                        
    let backLeftLegBack : Image                                                                                                                                                                                                      
    let backLeftLegMiddle : Image                                                                                                                                                                                                    
    let idleMario : Image                                                                                                                                                                                                            
    let jumpingMario : Image                                                                                                                                                                                                         
    let smallLeftLegUP :Image                                                                                                                                                                                                        
    let smallLeftLegBack : Image                                                                                                                                                                                                     
    let smallLeftLegMiddle : Image                                                                                                                                                                                                   
    let smallJumpingMario : Image                                                                                                                                                                                                    
    let smallIdleMario : Image                                                                                                                                                                                                       
    let marioSound : Audio                                                                                                                                                                                                           
                                                                                                                                                                                                                                     
    private var shouldPlayAudio = false                                                                                                                                                                                              
                                                                                                                                                                                                                                     
    //let smallbackLeftLegMiddle : Image                                                                                                                                                                                             
    //let smallbackLeftLegBack : Image                                                                                                                                                                                               
    //let smallbackLeftLegUP : Image                                                                                                                                                                                                 
    private var godMode = 25                                                                                                                                                                                                         
    private var isComingDown = false                                                                                                                                                                                                 
    private var loop = 0                                                                                                                                                                                                             
    private var runAnimation = false                                                                                                                                                                                                 
    private var frameCountForMario = 9                                                                                                                                                                                               
    private var marioPoint = Point(x:100,y:0)                                                                                                                                                                                        
    private var canvasBottom = 0                                                                                                                                                                                                     
    private var differentAnimation = 0                                                                                                                                                                                               
    private var marioSize = Size(width:0,height:0)                                                                                                                                                                                   
    private var marioHitPoint = 2                                                                                                                                                                                                    
    init() {                                                                                                                                                                                                                         
        // Using a meaningful name can be helpful for debugging                                                                                                                                                                      
                                                                                                                                                                                                                                     
        guard let LeftLegUPURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/LeftLegUP.png") else {                                                                                                             
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
        guard let marioSoundURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/aflac-duck.mp3") else {                                                                                                           
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
        guard let LeftLegBackURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/LeftLegBack.png") else {                                                                                                         
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
        guard let LeftLegMiddleURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/LeftLegMiddle.png") else {                                                                                                     
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
        guard let smallLeftLegUPURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/smallLeftLegUP.png") else {                                                                                                   
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
        guard let  smallLeftLegBackURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/smallLeftLegBack.png") else {                                                                                              
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
        guard let smallLeftLegMiddleURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/smallLeftLegMiddle.png") else {                                                                                           
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
        guard let BackLeftLegUPURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/LeftLegUPBack.png") else {                                                                                                     
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
        guard let smallBackLeftLegUPURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/LeftLegUPBack.png") else {                                                                                                
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
        
        }                                                                                                                                                                                                                            
        guard let BackLeftLegBackURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/LeftLegBackBack.png") else {                                                                                                 
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
        guard let BackLeftLegMiddleURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/LeftLegMiddleBack.png") else {                                                                                             
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
        guard let idleMarioURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/Idlemario.png") else {                                                                                                             
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
        guard let smallidleMarioURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/smallMarioIdle.png") else {                                                                                                   
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
        guard let jumpingMarioURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/JumpingMario.png") else {                                                                                                       
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
                                                                                                                                                                                                                                     
        }                                                                                                                                                                                                                            
        guard let smalljumpingMarioURL = URL(string:"https://www.codermerlin.com/users/rodrigo-suarez/ISP/smallJumpingMario.png") else {                                                                                             
            fatalError("Failed to create URL for whitehouse")                                                                                                                                                                        
        }                                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
        LeftLegUP = Image(sourceURL:LeftLegUPURL)                                                                                                                                                                                    
        LeftLegBack = Image(sourceURL:LeftLegBackURL)                                                                                                                                                                                
        LeftLegMiddle = Image(sourceURL:LeftLegMiddleURL)                                                                                                                                                                            
        backLeftLegUP = Image(sourceURL:BackLeftLegUPURL)                                                                                                                                                                            
        backLeftLegBack = Image(sourceURL:BackLeftLegBackURL)                                                                                                                                                                        
        backLeftLegMiddle = Image(sourceURL:BackLeftLegMiddleURL)                                                                                                                                                                    
        idleMario = Image(sourceURL:idleMarioURL)                                                                                                                                                                                    
        smallIdleMario = Image(sourceURL:smallidleMarioURL)                                                                                                                                                                          
        jumpingMario = Image(sourceURL:jumpingMarioURL)                                                                                                                                                                              
        smallLeftLegUP = Image(sourceURL:smallLeftLegUPURL)                                                                                                                                                                          
        smallLeftLegBack = Image(sourceURL:smallLeftLegBackURL)                                                                                                                                                                      
        smallLeftLegMiddle = Image(sourceURL:smallLeftLegMiddleURL)                                                                                                                                                                  
        smallJumpingMario = Image(sourceURL:smalljumpingMarioURL)                                                                                                                                                                    
        marioSound = Audio(sourceURL:marioSoundURL,shouldLoop:false)                                                                                                                                                                 
        super.init(name:"Mario")                                                                                                                                                                                                     
                                                                                                                                                                                                                                     
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
    override func setup(canvasSize:Size,canvas:Canvas){                                                                                                                                                                              
        marioSize = Size(width:canvasSize.width/26, height:(canvasSize.height/15))                                                                                                                                                   
                                                                                                                                                                                                                                     
        canvas.setup(LeftLegUP,LeftLegBack,LeftLegMiddle,backLeftLegUP,backLeftLegBack,backLeftLegMiddle,idleMario,jumpingMario,smallLeftLegUP,smallLeftLegBack,smallLeftLegMiddle,smallIdleMario,smallJumpingMario,marioSound)      
        canvasBottom = canvasSize.height  
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                     
    }                                                                                                                                                                                                                                
    public func getMode() -> Int{                                                                                                                                                                                                    
        return godMode                                                                                                                                                                                                               
    }                                                                                                                                                                                                                                
    func render(rectRowBuildingCount: Int, canvas:Canvas, topLeft:Point, size:Size, color:Color, fillcolor:Color,line:Int){                                                                                                          
        var rect = Rect(topLeft:topLeft, size:size)                                                                                                                                                                                  
        for _ in 0 ..< rectRowBuildingCount {                                                                                                                                                                                        
            let rectangle = Rectangle(rect:rect,fillMode:.fillAndStroke)                                                                                                                                                             
            let fillstyle = FillStyle(color:fillcolor)                                                                                                                                                                               
            let strokeStyle = StrokeStyle(color:color)                                                                                                                                                                               
            let linewidth = LineWidth(width:line)                                                                                                                                                                                    
            canvas.render(fillstyle,strokeStyle,linewidth,rectangle)                                                                                                                                                                 
            rect.topLeft = Point(x:rect.topLeft.x+size.width,y:rect.topLeft.y)                                                                                                                                                       
        }                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                
    public func changeHitPoint(_ hitpointNum:Int){                                                                                                                                                                                   
        marioHitPoint = hitpointNum                                                                                                                                                                                                  
    }                                                                                                                                                                                                                                
    public func gotHit(){                                                                                                                                                                                                            
        if marioHitPoint > 0{                                                                                                                                                                                                        
            marioHitPoint -= 1                                                                                                                                                                                                       
            shouldPlayAudio = true 
            }                                                                                                                                                                                                                            
        godMode = 25                                                                                                                                                                                                                 
    }                                                                                                                                                                                                                                
    func getHitpoint() -> Int {                                                                                                                                                                                                      
        return marioHitPoint                                                                                                                                                                                                         
    }                                                                                                                                                                                                                                
    public func getLocation() -> Point {                                                                                                                                                                                             
        return marioPoint                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                
    public func changeAnimation(_ animation:Int){                                                                                                                                                                                    
        differentAnimation = animation                                                                                                                                                                                               
    }                                                                                                                                                                                                                                
    override func boundingRect() -> Rect {                                                                                                                                                                                           
        if marioHitPoint == 1{                                                                                                                                                                                                       
            return Rect(topLeft:marioPoint,size:marioSize)                                                                                                                                                                           
        }else{                                                                                                                                                                                                                       
            return Rect(topLeft:marioPoint,size:Size(width:marioSize.width,height:marioSize.height*2))                                                                                                                               
        }                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                
    public func runningAnimation(_ running:Bool){                                                                                                                                                                                    
        if running{                                                                                                                                                                                                                  
            frameCountForMario = 6                                                                                                                                                                                                   
        } else {                                                                                                                                                                                                                     
            frameCountForMario = 9                                                                                                                                                                                                   
                                }                                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                
    override func render(canvas:Canvas){                                                                                                                                                                                             
        if godMode > 0 {                                                                                                                                                                                                             
            godMode -= 1                                                                                                                                                                                                             
        }                                                                                                                                                                                                                            
        if marioSound.isReady && shouldPlayAudio {                                                                                                                                                                                   
            canvas.render(marioSound)                                                                                                                                                                                                
            shouldPlayAudio = false                                                                                                                                                                                                  
        }                                                                                                                                                                                                                            
        guard let canvasSize = canvas.canvasSize else {                                                                                                                                                                              
            fatalError("no canvas Size")                                                                                                                                                                                             
        }                                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
        //render(rectRowBuildingCount:1,canvas:canvas,topLeft:boundingRect().topLeft,size:boundingRect().size ,color:Color(.blue),fillcolor:Color(.blue),line:1)                                                                     
                                                                                                                                                                                                                                     
        switch marioHitPoint {                                                                                                                                                                                                       
        case 0:                                                                                                                                                                                                                      
            print("dead")                                                                                                                                                                                                            
        case 1:                                                                                                                                                                                                                      
            switch differentAnimation {                                                                                                                                                                                              
            case 0:                                                                                                                                                                                                                  
                if smallIdleMario.isReady{                                                                                                                                                                                           
                                                                                                                                                                                                                                     
                    smallIdleMario.renderMode = .destinationRect(boundingRect())  
                    canvas.render(smallIdleMario)                                                                                                                                                                                    
                }                                                                                                                                                                                                                    
            case 1:                                                                                                                                                                                                                  
                if !isComingDown {                                                                                                                                                                                                   
                    if loop < frameCountForMario{                                                                                                                                                                                    
                        loop += 1                                                                                                                                                                                                    
                    }                                                                                                                                                                                                                
                    if loop >= frameCountForMario {                                                                                                                                                                                  
                        isComingDown = true                                                                                                                                                                                          
                    }                                                                                                                                                                                                                
                }else {                                                                                                                                                                                                              
                    if loop > 1 {                                                                                                                                                                                                    
                        loop -= 1                                                                                                                                                                                                    
                                                                                                                                                                                                                                     
                    }                                                                                                                                                                                                                
                    if loop == 1 {                                                                                                                                                                                                   
                        isComingDown = false                                                                                                                                                                                         
                    }                                                                                                                                                                                                                
                }                                                                                                                                                                                                                    
                if smallLeftLegUP.isReady && loop > ((frameCountForMario/3)*2){                                                                                                                                                      
                                                                                                                                                                                                                                     
                    smallLeftLegUP.renderMode = .destinationRect(boundingRect())                                                                                                                                                     
                    canvas.render(smallLeftLegUP)                                                                                                                                                                                    
                }                                                                                                                                                                                                                    
                   
                   if smallLeftLegBack.isReady && loop <= frameCountForMario/3 {                                                                                                                                                        
                    smallLeftLegBack.renderMode = .destinationRect(boundingRect())                                                                                                                                                   
                    canvas.render(smallLeftLegBack)                                                                                                                                                                                  
                }                                                                                                                                                                                                                    
                                                                                                                                                                                                                                     
                if smallLeftLegMiddle.isReady && loop>frameCountForMario/3 && loop <= ((frameCountForMario/3)*2){                                                                                                                    
                    smallLeftLegMiddle.renderMode = .destinationRect(boundingRect())                                                                                                                                                 
                    canvas.render(smallLeftLegMiddle)                                                                                                                                                                                
                }                                                                                                                                                                                                                    
                                                                                                                                                                                                                                     
            case 2:                                                                                                                                                                                                                  
                //loop = (loop+1)%frameCountForMario                                                                                                                                                                                 
                if !isComingDown {                                                                                                                                                                                                   
                    if loop < frameCountForMario{                                                                                                                                                                                    
                        loop += 1                                                                                                                                                                                                    
                    }                                                                                                                                                                                                                
                    if loop >= frameCountForMario {                                                                                                                                                                                  
                        isComingDown = true                                                                                                                                                                                          
                    }                                                                                                                                                                                                                
                }else {                                                                                                                                                                                                              
                    if loop > 1 {                                                                                                                                                                                                    
                        loop -= 1                                                                                                                                                                                                    
                                                                                                                                                                                                                                     
                    }                                                                                                                                                                                                                
                    if loop == 1 { 
                         isComingDown = false                                                                                                                                                                                         
                    }                                                                                                                                                                                                                
                }                                                                                                                                                                                                                    
                if backLeftLegUP.isReady && loop > ((frameCountForMario/3)*2){                                                                                                                                                       
                    backLeftLegUP.renderMode = .destinationRect(boundingRect())                                                                                                                                                      
                    canvas.render(backLeftLegUP)                                                                                                                                                                                     
                }                                                                                                                                                                                                                    
                if backLeftLegBack.isReady && loop <= frameCountForMario/3 {                                                                                                                                                         
                    backLeftLegBack.renderMode = .destinationRect(boundingRect())                                                                                                                                                    
                    canvas.render(backLeftLegBack)                                                                                                                                                                                   
                }                                                                                                                                                                                                                    
                if backLeftLegMiddle.isReady && loop>frameCountForMario/3 && loop <= ((frameCountForMario/3)*2){                                                                                                                     
                    backLeftLegMiddle.renderMode = .destinationRect(boundingRect())                                                                                                                                                  
                    canvas.render(backLeftLegMiddle)                                                                                                                                                                                 
                }                                                                                                                                                                                                                    
            case 3:                                                                                                                                                                                                                  
                if smallJumpingMario.isReady{                                                                                                                                                                                        
                    smallJumpingMario.renderMode = .destinationRect(boundingRect())                                                                                                                                                  
                    canvas.render(smallJumpingMario)                                                                                                                                                                                 
                }                                                                                                                                                                                                                    
            default :                                                                                                                                                                                                                
                fatalError("there is no number:\(differentAnimation) associated with this number ")                                                                                                                                  
            }                                                                                                                                                                                                                        
            case 2 :                                                                                                                                                                                                                 
                  
                  switch differentAnimation {                                                                                                                                                                                          
                case 0:                                                                                                                                                                                                              
                    if idleMario.isReady{                                                                                                                                                                                            
                                                                                                                                                                                                                                     
                        idleMario.renderMode = .destinationRect(boundingRect())                                                                                                                                                      
                        canvas.render(idleMario)                                                                                                                                                                                     
                    }                                                                                                                                                                                                                
                case 1:                                                                                                                                                                                                              
                    if !isComingDown {                                                                                                                                                                                               
                        if loop < frameCountForMario{                                                                                                                                                                                
                            loop += 1                                                                                                                                                                                                
                        }                                                                                                                                                                                                            
                        if loop >= frameCountForMario {                                                                                                                                                                              
                            isComingDown = true                                                                                                                                                                                      
                        }                                                                                                                                                                                                            
                    }else {                                                                                                                                                                                                          
                        if loop > 1 {                                                                                                                                                                                                
                            loop -= 1                                                                                                                                                                                                
                                                                                                                                                                                                                                     
                        }                                                                                                                                                                                                            
                        if loop == 1 {                                                                                                                                                                                               
                            isComingDown = false                                                                                                                                                                                     
                        }                                                                                                                                                                                                            
                    }                                                                                                                                                                                                                
                        
                        if LeftLegUP.isReady && loop > ((frameCountForMario/3)*2){                                                                                                                                                       
                                                                                                                                                                                                                                     
                        LeftLegUP.renderMode = .destinationRect(boundingRect())                                                                                                                                                      
                        canvas.render(LeftLegUP)                                                                                                                                                                                     
                    }                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
                    if LeftLegBack.isReady && loop <= frameCountForMario/3 {                                                                                                                                                         
                        LeftLegBack.renderMode = .destinationRect(boundingRect())                                                                                                                                                    
                        canvas.render(LeftLegBack)                                                                                                                                                                                   
                    }                                                                                                                                                                                                                
                    if LeftLegMiddle.isReady && loop>frameCountForMario/3 && loop <= ((frameCountForMario/3)*2){                                                                                                                     
                        LeftLegMiddle.renderMode = .destinationRect(boundingRect())                                                                                                                                                  
                        canvas.render(LeftLegMiddle)                                                                                                                                                                                 
                    }                                                                                                                                                                                                                
                case 2:                                                                                                                                                                                                              
                    loop = (loop+1)%frameCountForMario                                                                                                                                                                               
                    if backLeftLegUP.isReady && loop > ((frameCountForMario/3)*2){                                                                                                                                                   
                        backLeftLegUP.renderMode = .destinationRect(boundingRect())                                                                                                                                                  
                        canvas.render(backLeftLegUP)                                                                                                                                                                                 
                    }                                                                                                                                                                                                                
                    if backLeftLegBack.isReady && loop <= frameCountForMario/3 {                                                                                                                                                     
                        backLeftLegBack.renderMode = .destinationRect(boundingRect())                                                                                                                                                
                        canvas.render(backLeftLegBack)                                                                                                                                                                               
                    }                                                                                                                                                                                                                
                    if backLeftLegMiddle.isReady && loop>frameCountForMario/3 && loop <= ((frameCountForMario/3)*2){  
                        backLeftLegMiddle.renderMode = .destinationRect(boundingRect())                                                                                                                                              
                        canvas.render(backLeftLegMiddle)                                                                                                                                                                             
                    }                                                                                                                                                                                                                
                case 3:                                                                                                                                                                                                              
                    if jumpingMario.isReady{                                                                                                                                                                                         
                        jumpingMario.renderMode = .destinationRect(boundingRect())                                                                                                                                                   
                        canvas.render(jumpingMario)                                                                                                                                                                                  
                    }                                                                                                                                                                                                                
                default :                                                                                                                                                                                                            
                    fatalError("there is no number:\(differentAnimation) associated with this number ")                                                                                                                              
                }                                                                                                                                                                                                                    
                case 3:                                                                                                                                                                                                              
                    print()                                                                                                                                                                                                          
                default :                                                                                                                                                                                                            
                    fatalError("there is no number:\(marioHitPoint) associated with this number ")                                                                                                                                   
        }                                                                                                                                                                                                                            
                                                                                                                                                                                                                                     
    }                                                                                                                                                                                                                                
    func move (to point:Point) {                                                                                                                                                                                                     
        marioPoint = point                                                                                                                                                                                                           
                                                                                                                                                                                                                                     
    }                                                                                                                                                                                                                                
}     