import Igis                                                                                                                                                                                                                          
import Scenes                                                                                                                                                                                                                        
import Foundation                                                                                                                                                                                                                    
                                                                                                                                                                                                                                     
class Pole : RenderableEntity{                                                                                                                                                                                                       
    var polePoint = Point(x:0,y:0)                                                                                                                                                                                                   
    var poleSize = Size(width:0,height:0)                                                                                                                                                                                            
    init(){                                                                                                                                                                                                                          
        super.init(name:"Pole")                                                                                                                                                                                                      
    }                                                                                                                                                                                                                                
    override func setup(canvasSize:Size,canvas:Canvas){                                                                                                                                                                              
                                                                                                                                                                                                                                     
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
    override func render(canvas:Canvas){                                                                                                                                                                                             
        guard let canvasSize = canvas.canvasSize else {                                                                                                                                                                              
            fatalError("no canvas Size")                                                                                                                                                                                             
        }                                                                                                                                                                                                                            
        poleSize = Size(width:canvasSize.width/190,height:(canvasSize.height/15)*9)                                                                                                                                                  
        //ScenesShell.render(rectRowBuildingCount: 1, canvas: canvas, topLeft: polePoint, size: poleSize, color: Color(.red), fillcolor: Color(.red), line: 1)                                                                       
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
    func move(to point:Point){                                                                                                                                                                                                       
        polePoint = point                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                
    func getPoint() -> Point{                                                                                                                                                                                                        
        return polePoint                                                                                                                                                                                                             
    }                                                                                                                                                                                                                                
    override func boundingRect() -> Rect{                                                                                                                                                                                            
        return Rect(topLeft:polePoint,size:poleSize)                                                                                                                                                                                 
    }                                                                                                                                                                                                                                
                                                                                                                                                                                                                                     
}